# Site settings
title: "Hoite Prins"
description: "Hoite"
url: "https://hoite.github.io"
baseurl: ""

# Personal information
author:
  name: "Hoite Prins"
  email: "hoite.prins@gmail.com"
  bio: "Docent ICT, Nerd"
  location: "Zwolle, Netherlands"
  linkedin: "hoite-prins"
  github: "hoite"
  twitter: "hoite89"  # optional

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hoite"
