# Site settings
title: "Hoite - Digital Professional"
description: "Personal website and digital business card"
url: "https://hoite.github.io"
baseurl: ""

# Personal information
author:
  name: "Your Name"
  email: "your.email@example.com"
  bio: "Your professional bio goes here"
  location: "Your Location"
  linkedin: "your-linkedin-username"
  github: "hoite"
  twitter: "your-twitter-handle"  # optional

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
